### ISSUE TITLE
RISC-V is case sensitive

### ISSUE THREAD

**Issue by zeeshanrafique23** [maaz-siddiqui/RiscV-Logisim#2]
Please change the repo name as RISC-V is case sensitive and it should not be like a combination of both upper and lower case letters, and please change the .circ file name too and the name in the picture posted in the README.md

**Comment by maaz-siddiqui** [comment]
- [x] Circuit name : RISC-V
- [x] Repo name :  https://github.com/maaz-siddiqui/RISCV
- [x] Image name : RV32I-Circuit.png

**Comment by zeeshanrafique23** [comment]
Great thanks
